"""empty message

Revision ID: 2a0e5ccdb26a
Revises: 
Create Date: 2017-04-28 01:38:25.527069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a0e5ccdb26a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_table('wish_list_item',
    sa.Column('itemid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=80), nullable=True),
    sa.Column('website', sa.String(length=80), nullable=True),
    sa.Column('thumbnail', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('itemid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wish_list_item')
    op.drop_table('user_profile')
    # ### end Alembic commands ###
